/**
 * Mock coupon dataset with diverse test scenarios.
 *
 * Includes: percentage, flat, free shipping types; active and expired status;
 * varying minimums, categories, and edge cases (100% off, high minimum, etc.)
 */

import { Coupon } from '../types';

export const MOCK_COUPONS: Coupon[] = [
  {
    id: '1',
    code: 'SAVE20',
    description: 'Get 20% off on all courses. Perfect for your first purchase!',
    discountType: 'percentage',
    discountValue: 20,
    minimumOrderValue: 500,
    maxDiscount: 200,
    applicableCategories: ['all'],
    expiryDate: '2027-12-31T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '2',
    code: 'FLAT100',
    description: 'Flat ₹100 off on orders above ₹999. Limited time offer.',
    discountType: 'flat',
    discountValue: 100,
    minimumOrderValue: 999,
    applicableCategories: ['all'],
    expiryDate: '2027-06-30T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '3',
    code: 'FREESHIP',
    description: 'Free shipping on all orders. No minimum required!',
    discountType: 'free_shipping',
    discountValue: 0,
    minimumOrderValue: 0,
    applicableCategories: ['all'],
    expiryDate: '2027-09-15T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '4',
    code: 'SCIENCE30',
    description: '30% off on Science courses. Explore the universe of knowledge.',
    discountType: 'percentage',
    discountValue: 30,
    minimumOrderValue: 1000,
    maxDiscount: 500,
    applicableCategories: ['science'],
    expiryDate: '2027-08-31T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '5',
    code: 'EXPIRED50',
    description: 'This 50% discount has expired. Better luck next time!',
    discountType: 'percentage',
    discountValue: 50,
    minimumOrderValue: 200,
    maxDiscount: 1000,
    applicableCategories: ['all'],
    expiryDate: '2024-01-01T23:59:59.000Z',
    status: 'expired',
  },
  {
    id: '6',
    code: 'MEGA500',
    description: 'Mega deal! Flat ₹500 off on premium courses above ₹2000.',
    discountType: 'flat',
    discountValue: 500,
    minimumOrderValue: 2000,
    applicableCategories: ['all'],
    expiryDate: '2027-11-30T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '7',
    code: 'MATH15',
    description: '15% off on Mathematics courses. Unlock your potential.',
    discountType: 'percentage',
    discountValue: 15,
    minimumOrderValue: 300,
    applicableCategories: ['mathematics'],
    expiryDate: '2027-10-15T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '8',
    code: 'OLDFLAT',
    description: 'This flat discount offer has ended.',
    discountType: 'flat',
    discountValue: 250,
    minimumOrderValue: 500,
    applicableCategories: ['all'],
    expiryDate: '2023-06-30T23:59:59.000Z',
    status: 'expired',
  },
  {
    id: '9',
    code: 'WELCOME10',
    description: 'Welcome! Enjoy 10% off on your first course. No minimum!',
    discountType: 'percentage',
    discountValue: 10,
    minimumOrderValue: 0,
    applicableCategories: ['all'],
    expiryDate: '2027-12-31T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '10',
    code: 'FULL100',
    description: '100% off — completely free! Limited to select courses.',
    discountType: 'percentage',
    discountValue: 100,
    minimumOrderValue: 0,
    applicableCategories: ['science'],
    expiryDate: '2027-03-31T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '11',
    code: 'PREMIUM1K',
    description: 'Flat ₹1000 off on premium bundles. Minimum order ₹5000.',
    discountType: 'flat',
    discountValue: 1000,
    minimumOrderValue: 5000,
    applicableCategories: ['all'],
    expiryDate: '2027-07-31T23:59:59.000Z',
    status: 'active',
  },
  {
    id: '12',
    code: 'SHIPFREE2',
    description: 'Free shipping for orders above ₹499. Stock up and save!',
    discountType: 'free_shipping',
    discountValue: 0,
    minimumOrderValue: 499,
    applicableCategories: ['all'],
    expiryDate: '2027-05-31T23:59:59.000Z',
    status: 'active',
  },
];
