/**
 * Mock product catalog with realistic ecommerce data.
 * Categories match existing coupon applicableCategories (all, science, mathematics).
 */

import { CartItem } from '../types';

export const MOCK_PRODUCTS: CartItem[] = [
  {
    id: 'prod-1',
    name: 'Quantum Physics Masterclass',
    price: 1499,
    originalPrice: 2099,
    discountPercent: 29,
    quantity: 1,
    category: 'science',
    initials: 'QP',
    gradientColors: ['#7C3AED', '#4F46E5'],
    variant: 'Online · Lifetime Access',
    seller: 'PhysicsWorld Academy',
    rating: 4.8,
    discountBadge: 'BESTSELLER',
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'in_stock',
  },
  {
    id: 'prod-2',
    name: 'Advanced Calculus & Linear Algebra',
    price: 999,
    originalPrice: 1499,
    discountPercent: 33,
    quantity: 1,
    category: 'mathematics',
    initials: 'AC',
    gradientColors: ['#059669', '#10B981'],
    variant: 'Online · 6 Months Access',
    seller: 'MathPro Institute',
    rating: 4.6,
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'in_stock',
  },
  {
    id: 'prod-3',
    name: 'Organic Chemistry Fundamentals',
    price: 799,
    originalPrice: 999,
    discountPercent: 20,
    quantity: 1,
    category: 'science',
    initials: 'OC',
    gradientColors: ['#DC2626', '#F97316'],
    variant: 'Online · 3 Months Access',
    seller: 'ChemLearn Pro',
    rating: 4.4,
    discountBadge: 'NEW',
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'low_stock',
    stockCount: 4,
  },
  {
    id: 'prod-4',
    name: 'Data Science with Python',
    price: 1999,
    originalPrice: 3499,
    discountPercent: 43,
    quantity: 1,
    category: 'all',
    initials: 'DS',
    gradientColors: ['#2563EB', '#7C3AED'],
    variant: 'Online · Lifetime Access',
    seller: 'DataSkills Hub',
    rating: 4.9,
    discountBadge: 'POPULAR',
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'in_stock',
  },
  {
    id: 'prod-5',
    name: 'Statistics & Probability',
    price: 649,
    originalPrice: 899,
    discountPercent: 28,
    quantity: 1,
    category: 'mathematics',
    initials: 'SP',
    gradientColors: ['#D97706', '#F59E0B'],
    variant: 'Online · 6 Months Access',
    seller: 'StatsMaster',
    rating: 4.3,
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'low_stock',
    stockCount: 2,
  },
  {
    id: 'prod-6',
    name: 'Machine Learning A-Z',
    price: 2499,
    originalPrice: 4999,
    discountPercent: 50,
    quantity: 1,
    category: 'all',
    initials: 'ML',
    gradientColors: ['#0891B2', '#06B6D4'],
    variant: 'Online · Lifetime Access',
    seller: 'AI Pathways',
    rating: 4.9,
    discountBadge: 'TOP RATED',
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'in_stock',
  },
  {
    id: 'prod-7',
    name: 'Biology: Cells to Organisms',
    price: 599,
    originalPrice: 799,
    discountPercent: 25,
    quantity: 1,
    category: 'science',
    initials: 'BO',
    gradientColors: ['#16A34A', '#4ADE80'],
    variant: 'Online · 3 Months Access',
    seller: 'BioLearn Academy',
    rating: 4.2,
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'in_stock',
  },
  {
    id: 'prod-8',
    name: 'Number Theory & Cryptography',
    price: 1199,
    originalPrice: 1799,
    discountPercent: 33,
    quantity: 1,
    category: 'mathematics',
    initials: 'NT',
    gradientColors: ['#9333EA', '#C084FC'],
    variant: 'Online · 6 Months Access',
    seller: 'CryptoMath Labs',
    rating: 4.5,
    deliveryEstimate: 'Free · Instant Access',
    stockStatus: 'in_stock',
  },
];

/** Default cart — pre-populated with 3 items on launch */
export const DEFAULT_CART_ITEMS: CartItem[] = [
  { ...MOCK_PRODUCTS[0], quantity: 1 },
  { ...MOCK_PRODUCTS[1], quantity: 1 },
  { ...MOCK_PRODUCTS[2], quantity: 2 },
];
